### ISSUE TITLE
Can't select custom cover images with filenames containing '+'

### ISSUE THREAD

**Issue by OllieTerrance** [JosefNemec/Playnite#100]
For example, selecting `A+.png`, the `+` appears to be replaced by a space -- URL decoding shenanigans?  (Replacing with `%2B` in the filename works though.)

```
System.IO.FileNotFoundException: Could not find file 'Z:\...\A .png'.
File name: 'Z:\...\A .png'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   ...
   at System.Windows.Window.ShowDialog()
   at PlayniteUI.GamesEditor.EditGame(IGame game)
   at PlayniteUI.Controls.GamePopupMenu.Edit_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target,
                                                          RoutedEventArgs routedEventArgs)
   ...
   at System.Windows.Application.Run(Window window)
   at PlayniteUI.App.Main()
```

The error appears after pressing Save, selecting the image is fine in the Edit Game Details modal.

**Comment by JosefNemec** [comment]
Fix released in 1.4
