### ISSUE TITLE
Breakpoint A Breakpoint has been reached

### ISSUE THREAD

**Issue by 0x6A7232** [JosefNemec/Playnite#1056]
Left Playnite on with Rage of Mages 2: Necromancer running in foreground overnight; screen locked of course.  Logged back in the next day, ROM2 is still running but minimized, and I have a message from Playnite: "Breakpoint A Breakpoint has been reached" or similar.  Playnite re-launched fine when I opened it again.  
Playnite.log: https://pastebin.com/WgMK6xBc
PlayniteUI.exe.log (Microsoft generated, I think?): https://pastebin.com/8RWrpQfA

**Comment by JosefNemec** [comment]
Please go to `About` menu and create diagnostics package for me. Thank you

**Comment by 0x6A7232** [comment]
Hi, here is the resulting code:

50bd338c-28c0-4506-851f-a3df74ef7c13

Thanks

**Comment by Stifling-Bossness** [comment]
I have the same issue. With Playnite running in the background, I'll get Breakpoint A after about a day. Here's my diag code too:

78beac1e-249f-41a7-8d2e-9da4dee0e4d9

**Comment by tylerszabo** [comment]
Looking at the logs I'm wondering if there's a race condition that occurs when UWP apps are being updated during a scan

**Comment by JosefNemec** [comment]
Playnite is not UWP application. Also what do you mean by "during a scan"? During scan of what?

**Comment by tylerszabo** [comment]
Sorry, I meant it looks like Playnite is adding games from the logs; so I meant "scanning" directories. It's hitting an error when attempting to read `C:\Program Files\WindowsApps\Microsoft.Tomp_1.0.4723.0_x64__8wekyb3d8bbwe\AppxManifest.xml` and it occurs to me that it's possible that the application was updated between reads.

I've seen similar race conditions, so it stood out more than the network issues later in the file.

**Comment by Foshitz** [comment]
I´ve also had this issue a few times, some of them occur while playing a game and some of them occurs when computer has been untouched for a few hours.  
The last incident was yesterday in the middle of a gaming session in Euro Truck Simulator 2.
And the last time before that was back in march, I think.

Diagnostic package:
afbcd1f3-636c-4ad6-aaad-54d4377614f2

**Comment by JosefNemec** [comment]
Can you please attach screenshot of the crash when it occurs again? Thank you

**Comment by Foshitz** [comment]
![breakpoint-exception](https://user-images.githubusercontent.com/16353951/59115804-55b4ac80-894a-11e9-8a9f-2deb03b9950c.JPG)

See also new diagnostic package, created just after error message was seen and screenshot taken.
95c88462-5a2e-4b08-8dd8-091933010c63

**Comment by Foshitz** [comment]
I just got another one.
837adc14-6d76-40f0-b7a1-f8396f4d4df1

Have you seen any recurring or different changes between these diagnostic packages?

**Comment by JosefNemec** [comment]
This is really weird, the crash doesn't occur in any part of Playnite's code (it would result in different crash dialog and also crash info in log, which is currently missing). Which means that I have no real way of knowing what is causing it, unless we find a way to reproduce this on demand.

**Comment by Foshitz** [comment]
So it might be a crash, without being an actual crash?
It does say "breakpoint", so could it be that a cache of some sort is reaching max amount of data? 

Or just reaching a point where the client can't take it anymore and just gives up and kills itself? :p

**Comment by JosefNemec** [comment]
From little of what I was able to find out, it might be caused by "damaged" .NET Framework installation, maybe try repairing it. At this point there's nothing I can do about this until I have a way how to reproduce this in my environment (it doesn't happen on any of my systems).

**Comment by Foshitz** [comment]
Cool, I'll try a reinstall of the client when I get home!

**Comment by 0x6A7232** [comment]
Hey, what .NET Framework does Playnite use so we know which one to repair?

**Comment by JosefNemec** [comment]
4.6.2+

**Comment by Foshitz** [comment]
Reinstalled the Playnite-client about 3 weeks ago, haven´t had any issues since then.

**Comment by MaverickMartyn** [comment]
Just had this exact error on what I believe is the most current build (I installed it for the first time a couple of days ago).
If I had to guess, I'd wager you have a dependency that has something similar to JavaScripts `debugger;` keyword or C#'s `Debugger.Break();`.
That, or someone mistakenly called exceptions "breakpoints" in their error dialog.

**Comment by cresscendo** [comment]
Been using Playnite awhile and have had this breakpoint issue with a few different games. Today though, I received it while playing Doom (2016) so I thought I would submit a report. Didn't know if I should open a separate issue, so sorry if this isn't the right spot.

Here's my diag code: 9e2c0fa0-b6d3-43d1-855c-4c8a9e3c20cc

**Comment by Foshitz** [comment]
I got one of these today, without even touching the computer for over an hour.

Diagnostic package = c3b070d5-ecd7-4226-9495-e4040c0d32eb

**Comment by Gygun** [comment]
My PC is 24/7 on, and I'm having this error about 1 time every 2 days (It started like 1 year ago). Updated several times, changed windows (I'm on a fresh install). Still happening. Any ideas?
6ed247ad-8efe-4c68-8b45-5dcde37226f7

**Comment by JosefNemec** [comment]
I have no idea what's causing this.

@Gygun  Can you try something for me?
- Edit `Common.config` (it's in install folder, by default `%localappdata%\Playnite\Common.config`)
- Change `OfflineMode` property from `False` to `True`
- Restart Playnite and see if it occurs again

Please let me know if something changes after doing that, thanks.

**Comment by Gygun** [comment]
Done, I'll report back in a few days. Thanks for the hard work, Playnite is amazing!

**Comment by Gygun** [comment]
It seems to work fine this way. I'll report back if anything happens. Thanks.

**Comment by JosefNemec** [comment]
Thanks for the info, that's a good and bad news (good that we now probably know what causes it, bad that I'm not sure how to fix it).

**Comment by Gygun** [comment]
I have some bad news =(  
[https://puu.sh/Ftvvl/0722b6f96c.png](img)  
[https://puu.sh/FtvBE/a962630ce6.zip](url) (diag.zip)

**Comment by JosefNemec** [comment]
Then I have no idea, I think it might be caused by one of the decencies we use, but since it doesn't crash in part of application I can actually investigate (it's not a standard crash), I can't tell which one.

I will be updating all dependencies to latest version when [porting to new .NET runtime](https://github.com/JosefNemec/Playnite/issues/1141), but until then there's nothing I can do about this, sadly.

**Comment by Gygun** [comment]
It's just one crash in 5 days, don't worry. If you want me to run any program in the background just ask, I have no problem with that. 
One thing I didn't tell you is that I installed the portable version, all in one folder.

**Comment by JosefNemec** [comment]
I've made some changes in 7.5 that could potentially fix it. Please let me know if you notice some change after 7.5 update.

**Comment by Gygun** [comment]
Since I updated to 7.5, it didn't crash again! (good news!), but last time lasted like 5 days, Idk, it's too random tbh. 
I'll report back in a week just in case! Thanks.

**Comment by Gygun** [comment]
Ok, this happened today (I was not idle btw)  
[https://puu.sh/Fyvee/06215cfc50.png](https://puu.sh/Fyvee/06215cfc50.png)
[https://puu.sh/Fyvey/8619f1ffb5.png](https://puu.sh/Fyvey/8619f1ffb5.png)
[https://puu.sh/FyveP/c6e5bfd6a2.png](https://puu.sh/FyveP/c6e5bfd6a2.png)

**Comment by JosefNemec** [comment]
Can you upload `%appdata%\playnite\playnite.log` file (the one in diag package is not complete for some reason)? Thanks

**Comment by Gygun** [comment]
I checked it myself, didn't found trace of the error.

`2020-04-16 18:13:52.9580|INFO:Game Baldur's Gate: Enhanced Edition installed after 3334 seconds.`
(At 19.34 crashed)
`2020-04-16 19:43:05.0177|INFO:Application started from 'C:\Games\Playnite', with '--hidesplashscreen' arguments.`

I reinstalled Baldur's Gate EE, and was testing it with the gog client. I didn't even use Playnite =(

[Full Log](https://puu.sh/FyO6Q/ec3c9c3e4f.7z)

**Comment by Foshitz** [comment]
I just got it again.
I had been playing Modern Warfare for about 75 minutes, PC has been running since yesterday morning.

First, i got the "Unrecoverable error"
Then, "A breakpoint has been reached"
Followed by attached image:
![0xe0434352](https://user-images.githubusercontent.com/16353951/79682103-fa1ca600-821f-11ea-985e-6563125d9680.jpg)

Diag.pack = 05954864-dce6-49b6-90ce-9bfc5acf1057

**Comment by JosefNemec** [comment]
I have a new theory about what's causing this. I might be our Steam plugin. Can you please try [this version](https://github.com/JosefNemec/Playnite/files/4515298/SteamLibrary.zip) of Steam plugin to see if it fixes the issue?

If you are using [universal Steam metadata plugin](https://github.com/JosefNemec/PlaynitePlugin-SteamStoreMetadata) then you need to use [this version](https://github.com/JosefNemec/Playnite/files/4515300/UniversalSteamMetadata.zip), because it has probably the same issue as built-in Steam plugin.

**Comment by Foshitz** [comment]
I just backed up the existing files and replaced with the files from the first link.
Will report back with my findings!

**Comment by Foshitz** [comment]
I just backed up the original files, replaced them with the first link and rebooted my PC.
Will report back with my findings!

**Comment by gin9980** [comment]
just got this too, removed over a hundred games from the libary.

**Comment by RobLach** [comment]
Same issue: 

```
**Diag Code** 
eb846888-396d-408e-bb32-3d02b5266e57
```

**Comment by Foshitz** [comment]
I haven´t gotten any new issues, but I was away last week and have been shutting down my PC every night and left it off until coming home from work the next day. So my PC hasn´t been running for any longer periods, like it was when the issue first started (I'm using it as a additional radiator in my room during the winter-months).

**Comment by Gygun** [comment]
I think it's way more stable in recent versions (1 crash a week), but it keeps happening. Just got a crash. Log is clean, not mention of the error.

[Screen](https://puu.sh/FHu2f/608216bbe0.png)

`2020-05-07 13:12:17.6454|INFO:Starting League of Legends, e1030142-f059-437d-9e3d-7594988decde, 83910793-d6c1-493f-905b-0061b0f9ea5b, 00000000-0000-0000-0000-000000000000
2020-05-07 13:12:17.6454|INFO:Using generic controller start the game.
2020-05-07 13:12:17.6454|INFO:Activating game action File: C:\Games\League of Legends\LeagueClient.exe, , C:\Games\League of Legends
2020-05-07 13:12:17.6454|DEBUG:Starting process: C:\Games\League of Legends\LeagueClient.exe, , C:\Games\League of Legends
2020-05-07 13:12:17.7345|INFO:Started League of Legends game.

-CRASH-`

**Comment by JosefNemec** [comment]
@Gygun  Are you using [this plugin](https://github.com/JosefNemec/PlaynitePlugin-SteamStoreMetadata) by any chance? If so, then you also need to update it to latest version since it probably contains the same bug causing this crash. Btw this crash will not be ever logged in logs, you don't have to analyze them when this crash happens.

**Comment by Gygun** [comment]
I wasn't using that plugin. Last time I just updated the SteamLibrary.dll that you posted. But I'll try the Universal Steam plugin. Who knows, maybe it helps ¯\_(ツ)_/¯

**Comment by JosefNemec** [comment]
It won't help. It's using exactly the same code as built-in Steam plugin. However if you are still getting that crash, then the issue is not in Steam code at all.

**Comment by chocolatechipcats** [comment]
Don't know if this can help narrow it down any, but I occasionally get this error only when I've had a launched game running for more than a few hours. 

I've replaced the Steam plugin to see if that helps any.

**Comment by jasoncollege24** [comment]
Hi,

I received this from the portable version today. I left PlayNite running for 2 days, with Elder Scrolls Online launcher running for more than a day. The log is right after re-launching, and ESO is still running in the background. I haven't installed anything special.

c6108c4c-887b-43bd-91d9-6465f7cec056

**Comment by RealityExit** [comment]
I get this error fairly often, sometimes daily, and my logs also look clean. I'd be open to run any test or debug builds if it helps.

**Comment by JosefNemec** [comment]
To anybody having this issue, can you please try solutions from [this link](https://silicophilic.com/exception-breakpoint-0x80000003/), to see if it fixes the issue? Mainly the one related to restore of corrupted system files and memory check.

**Comment by JosefNemec** [comment]
To clarify my previous comment. I've spent quite a lot of time researching this and I've found that it's most likely related to some issue with the Windows installation. The crash doesn't occur in our code (that's why there's nothing in our logs related to the crash) and it's most likely related to some corrupted system library which Playnite (.NET specifically) uses.

**Comment by RealityExit** [comment]
For what it's worth I performed all the steps and identified no issues. Had another crash a few minutes ago.

**Comment by Bluscream** [comment]
I just encountered it too

**Comment by Gygun** [comment]
Like I said before. Happened to me with an old win, and with a fresh install (also different win iso), so I discard the "corrupted system files" thing. 
Still happening once a week. Today I woke up with the breakpoint error and a crash (there's usually no crash, only breakpoint error).

![NVIDIA_Share_2020-07-23_09-25-10](https://user-images.githubusercontent.com/17392081/88286871-d148f880-ccc7-11ea-83c5-eb95d63c4f14.png)

There was no trace of the error in the log, but It recorded something after it failed to create the .diag package. Here:  

```
2020-07-23 09:25:14.5230|ERROR:Failed to created diagnostics package.System.IO.FileLoadException: Could not load file or assembly 'System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Insufficient system resources exist to complete the requested service. (Exception from HRESULT: 0x800705AA)
File name: 'System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Playnite.Diagnostic.CreateDiagPackage(String path, String userActionsDescription)
   at Playnite.ViewModels.CrashHandlerViewModel.CreateDiagPackage()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by JosefNemec** [comment]
Missing `System.IO.Compression` dll would definitely point to something wrong with Windows or .NET Framework installation.

**Comment by MaverickMartyn** [comment]
I haven't had this error for a couple of weeks at the very least. I haven't reinstalled Windows, but I did clean out old .NET versions.
If we are sticking to the theory of something being awry with the .NET, people might want to try uninstalling old .NET and .NET Core versions, and reinstalling the latest ones.

**Comment by JosefNemec** [comment]
To anyone still having this issue, can you attach `debug.log` file from Playnite's program directory? Thank you

**Comment by JosefNemec** [comment]
Correction, I need `%appdata%\playnite\cef.log` file, which is currently not being sent with diag. package.

**Comment by Gygun** [comment]
here it is! [cef.log](https://puu.sh/GGCPD/6117ae4e29.log)

**Comment by cresscendo** [comment]
[cef.log](https://pastebin.com/nW1vErDH)
Happened in the middle of a game again. This is after a fresh Windows install a couple weeks ago as well, so it's happened before and after new install. My playnite database was backed up in G Drive though so I used that when I installed Playnite again, if that makes any difference. 

It's always during a game for me though, typically when I've been playing for at least an hour or two, and the window popup comes up in the foreground and tabs me out of games, which is the worst part.

**Comment by cresscendo** [comment]
[cef.log](https://pastebin.com/mnFRin62)
Happened in the middle of a game again. This is after a fresh Windows install a couple weeks ago as well, so it's happened before and after new install. My playnite database was backed up in G Drive though so I used that when I installed Playnite again, if that makes any difference.

It's always during a game for me though, typically when I've been playing for at least an hour or two, and the window popup comes up in the foreground and tabs me out of games, which is the worst part.

**Comment by Gygun** [comment]
I haven't had a crash since my last post. All I can remember is updating Playnite. Anyway, thank you for your hard work! I'll update again if anything happens.

**Comment by LeeThompson** [comment]
Still getting this periodically with Playnite 8.8.

Diagnostics Package: 5e51c19b-db26-4eb6-8b45-c1bbd015ec0d

**Comment by JosefNemec** [comment]
Question to anybody who's having this issue still: Do you have `DNS Client` service disabled for some reason, or have some 3rd party app or setup (changes in host file) that would affect how DNS in Windows works?

Also, please check `%appdata%\playnite\cef.log` file to see if you have tone of these warnings there:
`Failed to read DnsConfig`

**Comment by LeeThompson** [comment]
DNS Client and DNS cache are not disabled.

My gaming machine is very stock.

cef.log hasn't been updated since 11/23.

It does have a lot of crashing though:

```
[1123/195823.424:ERROR:network_service_instance_impl.cc(264)] Network service crashed, restarting service.
[1123/195823.457:ERROR:network_service_instance_impl.cc(264)] Network service crashed, restarting service.
[1123/195823.493:ERROR:network_service_instance_impl.cc(264)] Network service crashed, restarting service.
[1123/195823.525:ERROR:network_service_instance_impl.cc(264)] Network service crashed, restarting service.
[1123/195823.553:ERROR:network_service_instance_impl.cc(264)] Network service crashed, restarting service.
[1123/195823.576:ERROR:network_service_instance_impl.cc(264)] Network service crashed, restarting service.
[1123/195823.588:ERROR:network_service_instance_impl.cc(264)] Network service crashed, restarting service.
[1123/195823.601:ERROR:network_service_instance_impl.cc(264)] Network service crashed, restarting service.
[1123/195823.628:ERROR:network_service_instance_impl.cc(264)] Network service crashed, restarting service.
```

**Comment by chocolatechipcats** [comment]
I haven't had it in a while, but I did modify my hosts file to block a few domains. No changes to the DNS services.

**Comment by JosefNemec** [comment]
I've made another set of blind changes that could potentially fix this. If you are able to reproduce this with new 8.9 update, then please attach new diag. package and also content of `%localappdata%\Playnite\User Data\Crashpad\reports\`. Thank you

**Comment by JosefNemec** [comment]
Is there anybody that encountered this issue since 8.9 update? Can we consider it being fixed?

**Comment by chocolatechipcats** [comment]
I've not have it occur for a few months at this point.

**Comment by Gygun** [comment]
Not a single crash since November. Thank you Josef!

**Comment by LeeThompson** [comment]
I haven't got the breakpoint error, but I have had playnite crash a couple times so I guess progress?

**Comment by JosefNemec** [comment]
> I haven't got the breakpoint error, but I have had playnite crash a couple times so I guess progress?

Did you send out crash report? Do you have crash IDs?

**Comment by JosefNemec** [comment]
> What was it?

Probably some issue in CEF when it's used from 32-bit process (Playnite is a 32bit process even on 64bit systems). So I enabled `large address space aware` flag for Playnite and it looks like it helped. Which makes no sense to me to be honest, because Playnite never goes near 32bit process memory limit.

**Comment by LeeThompson** [comment]
@JosefNemec Unfortunately now Playnite just exits without any notification (since it's being caught by it's own exception handler I guess) but here's a diag package: b3fbb4ad-aeed-4f7b-a604-ee22b872ce2e

**Comment by JosefNemec** [comment]
> @JosefNemec Unfortunately now Playnite just exits without any notification (since it's being caught by it's own exception handler I guess) but here's a diag package: b3fbb4ad-aeed-4f7b-a604-ee22b872ce2e

There's no crash info in Playnite or CEF logs, so it must be a different issue.

**Comment by chocolatechipcats** [comment]
I've gotten a silent crash as well. Diag package at 62552c7b-5c1e-4ab9-bc02-3a1c0196b9ec.

An interesting thing to note is that I often got the breakpoint errors when I had left the Windows 7 version of Solitaire (available from Winaero) idling in the background for several hours after launching from Playnite, though I never really thought of it until now. Solitaire was also running when I had the silent crash.

**Comment by LeeThompson** [comment]
Haven't seen this in a long, long time (sign: not a complaint!)
