### ISSUE TITLE
Suddenly Crashing On Startup

### ISSUE THREAD

**Issue by LeeThompson** [JosefNemec/Playnite#1994]
I had a 'breakpoint' stop today and when I tried to relaunch Playnite it shows a crash handler which then goes away immediately.

Diag Package (got by forcing default theme):
5673b273-31d9-48a8-89d6-74fcf3f0880f

```
2020-09-08 17:36:52.9553|INFO:Application started from 'C:\Clients\Playnite', with '' arguments.
2020-09-08 17:36:53.1238|INFO:Loaded plugin: Bethesda Library Importer
2020-09-08 17:36:53.1238|INFO:Loaded plugin: DLSite Metadata Provider
2020-09-08 17:36:53.1238|INFO:Loaded 0 DLSite genres
2020-09-08 17:36:53.1677|INFO:Loaded plugin: Epic Store Library Importer
2020-09-08 17:36:53.1677|INFO:Loaded plugin: Extension Updater
2020-09-08 17:36:53.1677|INFO:Loaded plugin: F95Zone Metadata Provider
2020-09-08 17:36:53.2096|INFO:PluginCommon - Parse plugin localization file C:\Clients\Playnite\Extensions\GameActivity\localization\LocSource.xaml.
2020-09-08 17:36:53.2146|INFO:PluginCommon - Download https://api.github.com/repos/Lacro59/playnite-gameactivity-plugin/releases
2020-09-08 17:36:53.4774|INFO:PluginCommon - Find v0.12.1
2020-09-08 17:36:53.4774|INFO:Loaded plugin: Game Activity
2020-09-08 17:36:53.4834|INFO:Loaded plugin: GOG Library Importer
2020-09-08 17:36:53.4834|INFO:PluginCommon - Parse plugin localization file C:\Clients\Playnite\Extensions\HowLongToBeat\localization\LocSource.xaml.
2020-09-08 17:36:53.4834|INFO:PluginCommon - Download https://api.github.com/repos/Lacro59/playnite-howlongtobeat-plugin/releases
2020-09-08 17:36:53.7069|INFO:PluginCommon - Find v0.5.2
2020-09-08 17:36:53.7069|INFO:Loaded plugin: HowLongToBeat
2020-09-08 17:36:53.7069|INFO:Loaded plugin: Humble Library Importer
2020-09-08 17:36:53.7159|INFO:Loaded plugin: IGDB metadata provider
2020-09-08 17:36:53.7538|INFO:Loaded plugin: itch.io Library Importer
2020-09-08 17:36:53.7538|INFO:PluginCommon - Download https://api.github.com/repos/Lacro59/playnite-metadatalocal-plugin/releases
2020-09-08 17:36:53.9578|INFO:PluginCommon - Find v0.4.2
2020-09-08 17:36:53.9578|INFO:Loaded plugin: Metadata Local
2020-09-08 17:36:53.9578|INFO:Loaded plugin: Origin Library Importer
2020-09-08 17:36:53.9688|INFO:Loaded plugin: Screenshot Plugin
2020-09-08 17:36:53.9688|INFO:saved settings
2020-09-08 17:36:53.9688|INFO:b4126cd9c4e002eaf816fbb4526a628f
2020-09-08 17:36:53.9688|INFO:600x900
2020-09-08 17:36:53.9688|INFO:white_logo
2020-09-08 17:36:53.9688|INFO:Loaded plugin: SteamGridDB Metadata Provider
2020-09-08 17:36:54.0027|INFO:Loaded plugin: Steam Library Importer
2020-09-08 17:36:54.0117|INFO:PluginCommon - Parse plugin localization file C:\Clients\Playnite\Extensions\SuccessStory\localization\LocSource.xaml.
2020-09-08 17:36:54.0117|INFO:PluginCommon - Download https://api.github.com/repos/Lacro59/playnite-successstory-plugin/releases
2020-09-08 17:36:54.2860|INFO:PluginCommon - Find v0.10.1
2020-09-08 17:36:54.2860|INFO:Loaded plugin: Success Story
2020-09-08 17:36:54.2860|INFO:Loaded plugin: Universal Steam Metadata
2020-09-08 17:36:54.3259|INFO:Loaded plugin: Uplay Library Importer
2020-09-08 17:36:54.3259|INFO:Loaded plugin: VNDB Metadata Provider
2020-09-08 17:36:54.4605|INFO:Loaded script extension: C:\Clients\Playnite\Extensions\GameMediaTools_b507da26737d15a6b693851532c4e1f0\GameMediaTools.ps1
2020-09-08 17:36:54.4964|INFO:Loaded script extension: C:\Clients\Playnite\Extensions\LibraryExporter\LibraryExporter.ps1
2020-09-08 17:36:54.5224|INFO:Loaded script extension: C:\Clients\Playnite\Extensions\SteamAddGame\SteamAddGame.ps1
2020-09-08 17:36:54.7128|INFO:Opening db C:\Private\Data\Playnite
2020-09-08 17:36:54.8794|ERROR:Unhandled exception occured.System.Windows.Markup.XamlParseException: Cannot create unknown type '{http://schemas.microsoft.com/winfx/2006/xaml/presentation}DinamicResource'. ---> System.Xaml.XamlObjectWriterException: Cannot create unknown type '{http://schemas.microsoft.com/winfx/2006/xaml/presentation}DinamicResource'.
   at System.Xaml.XamlObjectWriter.WriteStartObject(XamlType xamlType)
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)
   --- End of inner exception stack trace ---
   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)
   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlObjectWriter objectWriter)
   at System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(DependencyObject container, IComponentConnector componentConnector, IStyleConnector styleConnector, List`1 affectedChildren, UncommonField`1 templatedNonFeChildrenField)
   at System.Windows.FrameworkTemplate.LoadContent(DependencyObject container, List`1 affectedChildren)
   at System.Windows.StyleHelper.ApplyTemplateContent(UncommonField`1 dataField, DependencyObject container, FrameworkElementFactory templateRoot, Int32 lastChildIndex, HybridDictionary childIndexFromChildID, FrameworkTemplate frameworkTemplate)
   at System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField`1 templateDataField, FrameworkElement container)
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.DockPanel.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Control.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Control.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by LeeThompson** [comment]
PlayniteUI.exe --forcedefaulttheme gets it to load so for some reason the theme has stopped working for no apparent reason.

**Comment by LeeThompson** [comment]
Updated  eMixedNite to 0.53 seems okay now but Playnite should be more robust with this stuff.

**Comment by JosefNemec** [comment]
I can't do anything about this crash, it's caused by a combination of plugin doing unsupported stuff and theme supporting that unsupported extension feature...
