### ISSUE TITLE
Updating extensions can fail because old instance of playnite (and plugin) is not fully closed while new one installing the update is already started

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/Playnite#2415]
**Describe the bug**
When i install / upgrade an already installed plugin (perhaps theme also but did not test that) the installation fails to delete the current install. This results in the plugin being in an uinstalled state after the restart and i have to install the plugin a 2nd time for it to become active again.

i also see this in playnite error log:

```
27-08 01:57:52.990|ERROR|ExtensionInstaller:Failed to install extension I:\Games\playnite\test\HTML_Exporter_2_0.pext
System.UnauthorizedAccessException: Access to the path 'HtmlExporterPlugin.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Playnite.Plugins.ExtensionInstaller.InstallPackedFile[T](String path, String nanifestFileName, String rootDir, Func`2 newMan)
   at Playnite.Plugins.ExtensionInstaller.InstallPackedExtension(String path)
   at Playnite.Plugins.ExtensionInstaller.InstallExtensionQueue()
27-08 01:57:52.994|ERROR|PlayniteApplication:Failed to finish installing extenions.
System.Exception: Failed to install or uninstall one or more extensions.
   at Playnite.Plugins.ExtensionInstaller.InstallExtensionQueue()
   at Playnite.PlayniteApplication..ctor(Application nativeApp, ApplicationMode mode, String defaultThemeName, CmdLineOptions cmdLine)
27-08 01:57:53.532|INFO|PlayniteApplication:Application started from 'I:\Games\playnite'
```

This seems to be cause with the old playnite instance not being fully closed at the time it starts the new instance which tries todo the update.
 

**To Reproduce**
Have Fast pc so playnite starts up really fast, or perhaps slow closing playnite and install the (same) plugin multiple time by double clicking the PEXT

**Screenshots**
You can see it in this screeenshot also looking at the PID, all the way on the bottom you see a closefile is happening of the dll from another (old) instance with a different PID while just before that the new instance with a different (new) PID is already trying todo the update

![image](https://user-images.githubusercontent.com/10714776/131098729-44bd10c0-9bc2-4ebe-be80-bcf723867bfa.png)

**Diagnostics ID**
03d01cfa-4c99-4ec9-96f6-77de0fa0a361

**Comment by JosefNemec** [comment]
Fixed in devel.
