### ISSUE TITLE
Failed to upload diagnostic package 

### ISSUE THREAD

**Issue by cnapolit** [JosefNemec/Playnite#3449]
### Bug Description

While creating a separate issue, I attempted to create a diagnostic package within the application.

It failed with the attached screenshot & exception at the end of the description.
Repeated attempts, re-opening the window, & restarting the app resulted in the same outcome.
Here is the resulting zip file: [diag.zip](https://github.com/JosefNemec/Playnite/files/11802012/diag.zip)

```
20-06 11:06:38.288|ERROR|CrashHandlerViewModel:Failed to upload diag package.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Playnite.Services.ServicesClient.UploadDiagPackage(String diagPath) in C:\projects\playnite\source\Playnite\Services\ServicesClient.cs:line 58
   at Playnite.ViewModels.CrashHandlerViewModel.<>c__DisplayClass43_0.<CreateDiagPackage>b__1(GlobalProgressActionArgs _) in C:\projects\playnite\source\Playnite\ViewModels\CrashHandlerViewModel.cs:line 255
   at Playnite.ViewModels.ProgressViewViewModel.<>c__DisplayClass22_0.<ActivateProgress>b__0() in C:\projects\playnite\source\Playnite\ViewModels\ProgressViewViewModel.cs:line 91
```

### Diagnostics ID

N/A

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/94765074/8129b89c-e708-4f72-9c43-b42d405e056c)

**Comment by JosefNemec** [comment]
Fixed on backend
