### ISSUE TITLE
Occasional NRE when accessing SelectedGames Property while performing search

### ISSUE THREAD

**Issue by cnapolit** [JosefNemec/Playnite#3450]
### Bug Description

When a plugin accesses the `IMainViewAPI.SelectedGames` property during a search in Fullscreen mode, a null reference exception is occasionally thrown. This can crash the application if not handled by the plugin.

I cannot recall seeing this for other plugins, but I don't use any others that are as active as Playnite Sounds.
Have not attempted to recreate in Desktop mode.

I've had a hard time reliably recreating it, but I've noticed it through natural use, development, & documenting unrelated theme issues.

I attempted to upload a diagnostics package, but it failed (documented here: https://github.com/JosefNemec/Playnite/issues/3449)
Here is the zip file instead: [diag.zip](https://github.com/JosefNemec/Playnite/files/11802052/diag.zip)

Edit: Looking at the copied text again, the property seems to be frequently throwing and eventually ends up causing the crash (probably due to incidental exception handling)

Below is the exception:
```
20-06 10:35:21.452|ERROR|ExtensionFactory:Failed to execute OnGameSelected method from Playnite Sounds plugin.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Playnite.FullscreenApp.API.MainViewAPI.<>c.<get_SelectedGames>b__3_0(GamesCollectionViewEntry a) in C:\projects\playnite\source\Playnite.FullscreenApp\Api\MainViewAPI.cs:line 30
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Playnite.FullscreenApp.API.MainViewAPI.get_SelectedGames() in C:\projects\playnite\source\Playnite.FullscreenApp\Api\MainViewAPI.cs:line 30
   at PlayniteSounds.PlayniteSounds.PlayMusicBasedOnSelected() in D:\a\PlayniteSound\PlayniteSound\PlayniteSounds.cs:line 1822
   at PlayniteSounds.PlayniteSounds.OnGameSelected(OnGameSelectedEventArgs args) in D:\a\PlayniteSound\PlayniteSound\PlayniteSounds.cs:line 186
   at Playnite.Plugins.ExtensionFactory.InvokeOnGameSelected(List`1 oldValue, List`1 newValue) in C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 725
20-06 10:35:23.937|DEBUG|BaseCollectionView:Refreshing collection view filter.
20-06 10:35:24.157|DEBUG|BaseCollectionView:Refreshing collection view filter.
20-06 10:35:25.687|DEBUG|BaseCollectionView:Refreshing collection view filter.
20-06 10:35:26.877|WARN |MainViewModelBase:Lost keyboard focus from known controls, trying to focus something.
20-06 10:35:26.877|DEBUG|MainViewModelBase:Focusing Playnite.FullscreenApp.Controls.CheckBoxEx Content: IsChecked:True
20-06 10:35:32.812|DEBUG|BaseCollectionView:Updating collection view settings.
20-06 10:35:40.470|DEBUG|WindowFactory:Show dialog window Playnite.FullscreenApp.Windows.MainMenuWindowFactory: 2509784c-0626-4ebf-a33b-177f2673c9b7
20-06 10:47:51.234|DEBUG|WindowFactory:Closing window Playnite.FullscreenApp.Windows.MainMenuWindowFactory: 2509784c-0626-4ebf-a33b-177f2673c9b7, True
20-06 10:48:01.640|DEBUG|BaseCollectionView:Refreshing collection view filter.
20-06 10:48:01.640|ERROR|ExtensionFactory:Failed to execute OnGameSelected method from Playnite Sounds plugin.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Playnite.FullscreenApp.API.MainViewAPI.<>c.<get_SelectedGames>b__3_0(GamesCollectionViewEntry a) in C:\projects\playnite\source\Playnite.FullscreenApp\Api\MainViewAPI.cs:line 30
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Playnite.FullscreenApp.API.MainViewAPI.get_SelectedGames() in C:\projects\playnite\source\Playnite.FullscreenApp\Api\MainViewAPI.cs:line 30
   at PlayniteSounds.PlayniteSounds.PlayMusicBasedOnSelected() in D:\a\PlayniteSound\PlayniteSound\PlayniteSounds.cs:line 1822
   at PlayniteSounds.PlayniteSounds.OnGameSelected(OnGameSelectedEventArgs args) in D:\a\PlayniteSound\PlayniteSound\PlayniteSounds.cs:line 186
   at Playnite.Plugins.ExtensionFactory.InvokeOnGameSelected(List`1 oldValue, List`1 newValue) in C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 725
20-06 10:48:03.172|DEBUG|BaseCollectionView:Refreshing collection view filter.
20-06 10:48:05.061|DEBUG|BaseCollectionView:Refreshing collection view filter.
20-06 10:48:05.250|DEBUG|BaseCollectionView:Refreshing collection view filter.
20-06 10:48:10.280|DEBUG|BaseCollectionView:Refreshing collection view filter.
20-06 10:48:12.347|DEBUG|BaseCollectionView:Refreshing collection view filter.
20-06 10:48:19.188|DEBUG|BaseCollectionView:Refreshing collection view filter.
20-06 10:48:19.188|ERROR|ExtensionFactory:Failed to execute OnGameSelected method from Playnite Sounds plugin.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Playnite.FullscreenApp.API.MainViewAPI.<>c.<get_SelectedGames>b__3_0(GamesCollectionViewEntry a) in C:\projects\playnite\source\Playnite.FullscreenApp\Api\MainViewAPI.cs:line 30
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Playnite.FullscreenApp.API.MainViewAPI.get_SelectedGames() in C:\projects\playnite\source\Playnite.FullscreenApp\Api\MainViewAPI.cs:line 30
   at PlayniteSounds.PlayniteSounds.PlayMusicBasedOnSelected() in D:\a\PlayniteSound\PlayniteSound\PlayniteSounds.cs:line 1822
   at PlayniteSounds.PlayniteSounds.OnGameSelected(OnGameSelectedEventArgs args) in D:\a\PlayniteSound\PlayniteSound\PlayniteSounds.cs:line 186
   at Playnite.Plugins.ExtensionFactory.InvokeOnGameSelected(List`1 oldValue, List`1 newValue) in C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 725
20-06 10:48:21.186|DEBUG|BaseCollectionView:Refreshing collection view filter.
20-06 10:48:22.907|DEBUG|BaseCollectionView:Refreshing collection view filter.
20-06 10:48:23.874|DEBUG|BaseCollectionView:Refreshing collection view filter.
20-06 10:48:30.389|WARN |MainViewModelBase:Lost keyboard focus from known controls, trying to focus something.
20-06 10:48:30.389|DEBUG|MainViewModelBase:Focusing Playnite.FullscreenApp.Controls.CheckBoxEx Content: IsChecked:True
20-06 10:48:30.403|ERROR|PlayniteApplication:Unhandled exception occured.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Playnite.FullscreenApp.API.MainViewAPI.<>c.<get_SelectedGames>b__3_0(GamesCollectionViewEntry a) in C:\projects\playnite\source\Playnite.FullscreenApp\Api\MainViewAPI.cs:line 30
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Playnite.FullscreenApp.API.MainViewAPI.get_SelectedGames() in C:\projects\playnite\source\Playnite.FullscreenApp\Api\MainViewAPI.cs:line 30
   at PlayniteSounds.PlayniteSounds.ReplayMusic() in D:\a\PlayniteSound\PlayniteSound\PlayniteSounds.cs:line 489
   at PlayniteSounds.PlayniteSounds.MediaEnded(Object sender, EventArgs e) in D:\a\PlayniteSound\PlayniteSound\PlayniteSounds.cs:line 724
   at System.Windows.Media.UniqueEventHelper.InvokeEvents(Object sender, EventArgs args)
   at System.Windows.Media.MediaEventsHelper.OnMediaEnded(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at Playnite.FullscreenApp.Windows.TextInputWindow.ShowInput(Window owner, String messageBoxText, String caption, String defaultInput, List`1 options) in C:\projects\playnite\source\Playnite.FullscreenApp\Windows\TextInputWindow.xaml.cs:line 158
   at Playnite.FullscreenApp.ViewModels.FullscreenAppViewModel.<InitializeCommands>b__250_16(Object a) in C:\projects\playnite\source\Playnite.FullscreenApp\ViewModels\FullscreenAppViewModel_Commands.cs:line 254
   at Playnite.SDK.RelayCommand`1.Execute(Object parameter) in C:\projects\playnite\source\PlayniteSDK\RelayCommand.cs:line 205
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.Input.KeyEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at Playnite.Input.XInputDevice.<>c__DisplayClass47_0.<SendXInput>b__0(Object a) in C:\projects\playnite\source\Playnite\Input\XInputBinding.cs:line 465
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Playnite.FullscreenApp.ProgramEntry.Main(String[] args) in C:\projects\playnite\source\Playnite.FullscreenApp\ProgramEntry.cs:line 61
```

### Diagnostics ID

N/A

**Comment by JosefNemec** [comment]
Fixed in master
