### ISSUE TITLE
Library disappeared with latest update

### ISSUE THREAD

**Issue by CetaceanNation** [JosefNemec/Playnite#3589]
### Bug Description

As title says, all games disappeared after the latest update. This doesn't seem to be specific to any plugin, I can reproduce the issue when trying to refresh both my Steam library and my GOG library. In the log I get the following for every game entry returned by a plugin:
```
25-10 22:10:56.661|INFO |GameDatabase:Adding new game 1207658920 from GOG plugin
25-10 22:10:56.661|ERROR|GameDatabase:Failed to import game into database.
System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at LiteDB.FileDiskService.ReadPage(UInt32 pageID)
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.CollectionService.Get(String name)
   at LiteDB.LiteEngine.GetCollectionPage(String name, Boolean addIfNotExits)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonType autoId)
   at LiteDB.LiteCollection`1.Upsert(IEnumerable`1 documents)
   at LiteDB.LiteCollection`1.Upsert(T document)
   at Playnite.Database.ItemCollection`1.Add(TItem itemToAdd) in C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:line 373
   at Playnite.Database.GamesCollection.Add(Game item) in C:\projects\playnite\source\Playnite\Database\Collections\GamesCollection.cs:line 85
   at Playnite.Database.GameDatabase.ImportGame(GameMetadata game, Guid pluginId) in C:\projects\playnite\source\Playnite\Database\GameDatabase.cs:line 1181
   at Playnite.Database.GameDatabase.ImportGames(LibraryPlugin library, CancellationToken cancelToken, PlaytimeImportMode playtimeImportMode) in C:\projects\playnite\source\Playnite\Database\GameDatabase.cs:line 1248
25-10 22:10:56.661|INFO |MainViewModelBase:Starting Library Install Size scan
25-10 22:10:56.661|INFO |MainViewModelBase:Finished Library Install Size scan
25-10 22:10:57.671|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 24b88c7f-fc2e-44c5-842f-37227c708400
25-10 22:10:57.751|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 24b88c7f-fc2e-44c5-842f-37227c708400, True
```
This issue also applies to the games I do not have from library integrations and made manual entries for.

### To Reproduce

Update to 10.20, not sure what specifically caused this.

### Diagnostics ID

5fa00e51-144a-4127-abac-2a815826687a

### Screenshots

No filters applied.
![image](https://github.com/JosefNemec/Playnite/assets/32624140/c6e997af-23c5-43d0-ab75-e445c5b482f3)

**Comment by JosefNemec** [comment]
Your library files are most likely corrupted, go to `%appdata%\playnite\library\` and upload .db files you find there.

Btw definitely not related to 10.20 update, there was no change in library data handling.

**Comment by CetaceanNation** [comment]
Appreciate your time, thank you.
[library.zip](https://github.com/JosefNemec/Playnite/files/13183741/library.zip)

**Comment by JosefNemec** [comment]
Thanks for the files. Unfortunately the main `games.db` file is damaged in a way that's not simple to recover. Not sure what caused the corruption, nothing really wrong in the logs. Corruptions are very rare but I recommend enabling internal backup feature to have recovery available in future.

You'll have to delete the file and let Playnite recreate the library.
