### ISSUE TITLE
Playnite Launch / Updates finish

### ISSUE THREAD

**Issue by KuhanR** [JosefNemec/Playnite#3654]
### Bug Description

Once Playnite launches and goes through usual updates, once finished receive the following

<img width="462" alt="image" src="https://github.com/JosefNemec/Playnite/assets/45024759/4b836279-e6c9-4600-8086-de67c6d28742">

### Diagnostics ID

26fe2a72-425f-4166-8711-947d577b2f8c

### Screenshots

<img width="462" alt="image" src="https://github.com/JosefNemec/Playnite/assets/45024759/94cd6731-c522-4274-b12b-0dfdf90926e4">

**Comment by JosefNemec** [comment]
Caused by LinkUtilities plugin, please report it to its developer:

> System.NullReferenceException: Object reference not set to an instance of an object.
   at LinkUtilities.LinkUtilities.Games_ItemUpdated(Object sender, ItemUpdatedEventArgs`1 args) in C:\Alex\Entwicklung\dotnet\Playnite-Extensions\Generic\LinkUtilities\LinkUtilities.cs:line 177
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
