### ISSUE TITLE
Steam metadata download failure

### ISSUE THREAD

**Issue by lef-est** [JosefNemec/Playnite#3806]
### Bug Description

error message: `object reference not set to an instance of an object`

from log:
```
25-08 02:29:42.711|ERROR|GameEditViewModel:Failed to download metadata, cb91dfc9-b977-43bf-8e70-55f46e410fab, 373600
System.NullReferenceException: Object reference not set to an instance of an object.
   at Steam.MetadataProvider.GetSteamDeckCompatibility(KeyValue productDetails) in C:\Devel\PlayniteExtensions\source\Libraries\SteamLibrary\SteamShared\MetadataProvider.cs:line 542
   at Steam.MetadataProvider.GetGameMetadata(UInt32 appId, BackgroundSource backgroundSource, Boolean downloadVerticalCovers, Boolean downloadParentMetadata) in C:\Devel\PlayniteExtensions\source\Libraries\SteamLibrary\SteamShared\MetadataProvider.cs:line 496
   at SteamLibrary.SteamMetadataProvider.GetMetadata(Game game) in C:\Devel\PlayniteExtensions\source\Libraries\SteamLibrary\SteamMetadataProvider.cs:line 57
   at Playnite.DesktopApp.ViewModels.GameEditViewModel.<DownloadStoreData>b__512_0(GlobalProgressActionArgs args) in C:\projects\playnite\source\Playnite.DesktopApp\ViewModels\GameEditViewModelMetadata.cs:line 651
   at Playnite.ViewModels.ProgressViewViewModel.<>c__DisplayClass22_0.<ActivateProgress>b__0() in C:\projects\playnite\source\Playnite\ViewModels\ProgressViewViewModel.cs:line 91
```
From the log I see that the same thing happened before sporadically but today is the first time I get this error repeatedly for all Steam games I tried.
Reinstalling the Steam Library integration extension did not help.

### To Reproduce

Use `Download Metadata...` > `Official Store` on Steam games or `Download Metadata...` > `Steam Store` on any game.

### Diagnostics ID

506e7946-eab9-4285-9489-6dedffe9cccc

**Comment by Jeshibu** [comment]
This will be moved to https://github.com/JosefNemec/PlayniteExtensions, but I can reproduce this issue since a few hours. Also Universal Steam Metadata just fails silently after thinking for a good few seconds.
