### ISSUE TITLE
Crash when adding new game

### ISSUE THREAD

**Issue by neronix17** [JosefNemec/Playnite#588]
After clicking "Browse..." or "Scan Folder..." on the "Select Games to Import" screen it comes up with an error and is forced to close. I actually cannot get a diag package saved either since clicking that causes it to stop responding and it eventually crashes completely. It's likely caused by the last folder it was directed to not being available anymore. Here's the error that comes up since I can't get the diag package:

`System.ArgumentNullException: Value cannot be null.
Parameter name: inputSource
   at System.Windows.Input.KeyEventArgs..ctor(KeyboardDevice keyboard, PresentationSource inputSource, Int32 timestamp, Key key)
   at PlayniteUI.XInputEventArgs..ctor(Key key, XInputButtonState state, XInputButton button)
   at PlayniteUI.XInputDevice.<>c__DisplayClass24_0.<SendXInput>b__0(Object a)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)`

**Comment by JosefNemec** [comment]
Looks like some issue related to controller handling, if you disconnect the controller does it still occur?

**Comment by JosefNemec** [comment]
Just found where the problem, it occurs if controller is being used while any system dialog (like folder selection) is opened.

**Comment by JosefNemec** [comment]
Released in 4.21
