### ISSUE TITLE
Crash on startup: Could not load file or assembly CefSharp.Core

### ISSUE THREAD

**Issue by bburky** [JosefNemec/Playnite#849]
Playnite is crashing on startup. This occurs when installed or when run as a portable app.

This issue looks very similar to #562. CefSharp.Core.dll does exist in the installation directory.

```
2018-12-05 18:01:03.1174|INFO:Application started from 'C:\Users\Blake\Desktop\Playnite462\PlayniteUI.exe', with '' arguments.
2018-12-05 18:01:03.1643|ERROR:Unhandled exception occured.System.IO.FileLoadException: Could not load file or assembly 'CefSharp.Core, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' or one of its dependencies. The specified resource name cannot be found in the image file. (Exception from HRESULT: 0x80070716)
File name: 'CefSharp.Core, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'
   at PlayniteUI.CefTools.ConfigureCef()
   at PlayniteUI.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at PlayniteUI.ProgramEntry.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by JosefNemec** [comment]
Please go to `About` menu and generate diag. package for me, thank you.

**Comment by JosefNemec** [comment]
Nevermind, you obviously can't do that :) Anyways I found diag package from original crash report, which sadly didn't help much.

Could you please start PowerShell on your system, run following script and send me generated `hashes.csv`?
```
Get-ChildItem "c:\playnite_install_path\" -Recurse | Get-FileHash -Algorithm MD5 |
Export-Csv "c:\some_other_path\hashes.csv"
```

Don't forget to change paths to be appropriate for your system. Thank you

**Comment by bburky** [comment]
Here are the hashes you requested: [hashes.txt](https://github.com/JosefNemec/Playnite/files/2655364/hashes.txt) (Apparently GitHub will let you attach .txt files but not .csv?)

Also, I set the registry key mentioned in that error if it helps. Here is the same error with some additional info:
```
2018-12-06 17:56:37.1547|INFO:Application started from 'C:\Users\Blake\Desktop\Playnite462\PlayniteUI.exe', with '' arguments.
2018-12-06 17:56:37.2329|ERROR:Unhandled exception occured.System.IO.FileLoadException: Could not load file or assembly 'CefSharp.Core, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' or one of its dependencies. The specified resource name cannot be found in the image file. (Exception from HRESULT: 0x80070716)
File name: 'CefSharp.Core, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'
   at PlayniteUI.CefTools.ConfigureCef()
   at PlayniteUI.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at PlayniteUI.ProgramEntry.Main(String[] args)

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Users\Blake\Desktop\Playnite462\PlayniteUI.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = CefSharp.Core, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
 (Fully-specified)
LOG: Appbase = file:///C:/Users/Blake/Desktop/Playnite462/
LOG: Initial PrivatePath = NULL
Calling assembly : PlayniteUI, Version=4.62.0.30646, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\Blake\Desktop\Playnite462\PlayniteUI.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: CefSharp.Core, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
LOG: Attempting download of new URL file:///C:/Users/Blake/Desktop/Playnite462/CefSharp.Core.DLL.
ERR: Failed to complete setup of assembly (hr = 0x80070716). Probing terminated.
```

If it matters I'm currently on Windows 10, Version 1809, OS Build 17763.168

**Comment by bburky** [comment]
I have no idea what I'm doing with fuslogvw.exe, but it appears to have a little more detail for the errors on loading CefSharp.core:

```
*** Assembly Binder Log Entry  (2018-12-06 @ 18:54:47) ***

The operation failed.
Bind result: hr = 0x80070716. The specified resource name cannot be found in the image file.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Users\Blake\Desktop\Playnite462\PlayniteUI.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = CefSharp.Core, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
 (Fully-specified)
LOG: Appbase = file:///C:/Users/Blake/Desktop/Playnite462/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = PlayniteUI.exe
Calling assembly : PlayniteUI, Version=4.62.0.30646, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\Blake\Desktop\Playnite462\PlayniteUI.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: CefSharp.Core, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Users/Blake/Desktop/Playnite462/CefSharp.Core.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\Users\Blake\Desktop\Playnite462\CefSharp.Core.dll
LOG: Entering run-from-source setup phase.
ERR: Error extracting manifest import from file (hr = 0x80070716).
ERR: Run-from-source setup phase failed with hr = 0x80070716.
ERR: Failed to complete setup of assembly (hr = 0x80070716). Probing terminated.
```

**Comment by JosefNemec** [comment]
Thanks for additional information. I have absolutely no clue what might be causing this. Initially I thought that this might be caused by the Windows October update, but there are people using Playnite on 1809 without any issues.

Could you try [this build](https://playnite.link/download/CefSharpSerialization.zip) to see if it fixes the issue (I'm trying some things blindly)?

**Comment by bburky** [comment]
Sorry, doesn't work either. Errors look to be identical.

**Comment by bburky** [comment]
I managed to reproduce and fix this crazy bug. I like to try out all the Windows security and virtualization features and had run the [Device Guard and Credential Guard hardware readiness tool](https://www.microsoft.com/en-us/download/details.aspx?id=53337). It happens to also enable User Mode Code Integrity (UMCI). After very carefully Googling for error codes, I found an instance of [another program using CefSharp that broke with the same error](https://community.powerbi.com/t5/Desktop/Cannot-Start-Power-BI-desktop-64-or-32-bit/td-p/537491). Apparently as of 1809, UMCI breaks CefSharp? I've let one of the CefSharp developers know, I will probably file a bug.

If anyone else manages to have this problem delete `C:\Windows\System32\CodeIntegrity\SIPolicy.p7b` to remove the policy completely. Or you probably can disable only UMCI, but I didn't try.

**Comment by JosefNemec** [comment]
Thanks for an update on this. Can you please post a link to cefsharp bug? I would like to know when it's fixed and update cefsharp in Playnite after that. This could be serious issue for Playnite if UMCI is enabled for all users in future. I will also leave this open until we update cefsharp to working version.

**Comment by JosefNemec** [comment]
[Here's build](https://playnite.link/download/CefSharpUpdate.zip) with updated CefSharp, let me know if it fixes the issue for you.

**Comment by bburky** [comment]
I filed a bug report on CefSharp, linked above, we'll see if they manage to fix it somehow.

Sorry, that build doesn't work either. I also tested building their CefSharp.MinimalExample program using the latest 69.0.0 version. Windows appears to completely block CefSharp.Core.dll from loading and I can't even build the CefSharp.MinimalExample project. The build fails with the same 0x80070716 error as a build error.

**Comment by bburky** [comment]
The upstream cefsharp/CefSharp#2610 issue has been closed. Apparently [KB4487044](https://support.microsoft.com/en-us/help/4487044/windows-10-update-kb4487044) fixes the issue (build 17763.316 from 12 February 2019).

I can confirm I can now start Playnite while it is enabled.

**Comment by fernando89c** [comment]
If someone is still having this issue, try to install the VS C++ 2015 Redist: https://www.microsoft.com/pt-br/download/details.aspx?id=48145

This worked for me.

**Comment by JosefNemec** [comment]
Installing VC++ redist files shouldn't be needed because we distribute those with Playnite. I tested it and Playnite starts properly on my test machine if 2015 redist files are not installed. I don't think that's the root cause of your issue, but it's interesting that it fixed it for you.

**Comment by fernando89c** [comment]
Yes, I saw the file in the installation folder. I tried the portable
version and the problem persisted. After a long google search, i found the
solution on a ms office forum. Looks like its a windows problem. Im
using a win7 with SP1 recently formatted. Maybe its helps someone in the
same situation. What matters is that my daughter and I can now play snes
TMNT on TV during the quarantine. Thanks for your software, its great.

Em seg., 23 de mar. de 2020 às 11:22, Josef Nemec <notifications@github.com>
escreveu:

**Comment by amaitland** [comment]
What dlls are being packaged with your installer?

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/Playnite/tree/master/references/CefSharpRedist

**Comment by amaitland** [comment]
See https://devblogs.microsoft.com/cppblog/introducing-the-universal-crt/

Windows 10 already has the Universal CRT installed as part of the OS. Windows 7 you need to install the Universal CRT, which is included as part of the VC++ Resist or distribute the relevant dlls.

There is a separate installer for the Universal CRT see https://support.microsoft.com/en-au/help/2999226/update-for-universal-c-runtime-in-windows

**Comment by JosefNemec** [comment]
Thanks for all that info, I'll start including CRT files as well.
